version: "3.9"
services:
    app:
        image: ${DOCKER_HUB_USER}/${IMAGE_REPO}:${RELEASE_VERSION}
        restart: always
        container_name: ${IMAGE_REPO}-app
        environment:
            VIRTUAL_HOST: ${HOST_DOMAIN}
            LETSENCRYPT_HOST: ${HOST_DOMAIN}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        volumes:
            - app-mydb:/app/App_Data
    # app-migration:
    #     image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION}
    #     restart: "no"
    #     container_name: ${IMAGE_REPO}-app-migration
    #     profiles:
    #         - migration
    #     command: --AppTasks=migrate
    #     volumes:
    #         - app-mydb:/app/App_Data

networks:
  default:
    external: true
    name: app-net

volumes:
    app-mydb:
